services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
