version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
